services:
  api_dev:
    build: .
    volumes:
      - /usr/src/app
    ports:
      - '${PORT}:4000'
    command: npm run start:dev
    networks:
      - framedata_network
    restart: always
    expose:
      - 4000

networks:
  framedata_network:
    external: true
